#!/bin/zsh

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set LSCOLORS (FreeBSD / macOS).
#
#  * `ls` displays colors if the `-G` option is passed or if
#    the `CLICOLOR` environment variable is set.
#
#  * The actual colors are configured through the `LSCOLORS`
#    environment variable (built-in defaults are used if this
#    variable is not set).

LS_COLORS=""

LS_COLORS+="gx" # Directory
LS_COLORS+="fx" # Symbolic link
LS_COLORS+="cx" # Socket
LS_COLORS+="dx" # Pipe
LS_COLORS+="cx" # Executable
LS_COLORS+="eg" # Block special
LS_COLORS+="ed" # Character special
LS_COLORS+="ab" # Executable with setuid bit set
LS_COLORS+="ag" # Executable with setgid bit set
LS_COLORS+="cc" # Directory writable to others, with sticky bit
LS_COLORS+="bd" # Directory writable to others, without sticky bit

export LS_COLORS
export CLICOLOR=1

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Enable color support.

alias ls="ls -G"
