#!/bin/zsh

# inspired by http://natelandau.com/my-mac-osx-bash_profile/

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Make terminal better

alias ~="cd ~"                              # Go Home
alias cd..="cd ../"                         # Go back 1 directory level (for fast typers)
alias ..="cd ../"                           # Go back 1 directory level
alias ...="cd ../../"                       # Go back 2 directory levels
alias ....="cd ../../../"                   # Go back 3 directory levels
alias wks="cd ~/Workspace"                  # Go to workspace
alias less="less -FSRXc"                    # Preferred "less" implementation
alias cp="cp -iv"                           # Preferred "cp" implementation
alias mv="mv -iv"                           # Preferred "mv" implementation
alias ls="ls -GFh"                          # Preferred "ls" implementation
alias rm="rm -rf --"                        # Preferred "rm" implementation
alias mkdir="mkdir -pv"                     # Preferred "mkdir" implementation
alias f="open -a Finder ./"                 # Opens current directory in MacOS Finder
alias c="clear"                             # Clear terminal display
alias o="open"                              # Open from the terminal
alias g="git"                               # Run Git
alias which="type -all"                     # Find executables
alias path="echo -e ${PATH//:/\\n}"         # Echo all executable Paths

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Networking

alias myip='ipconfig getifaddr en0'         # Public facing IP Address
alias clear-dns-cache="sudo dscacheutil -flushcache; \
                       sudo killall -HUP mDNSResponder" # Flush out the DNS Cache
alias openPorts='sudo lsof -i | grep LISTEN'# All listening connections

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Git

alias s="git status"
alias p="git pull"
alias d="git d"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Shorter commands for `Homebrew`.

alias brewi="brew install"
alias brewr="brew uninstall"
alias brews="brew search"
alias brewup="brew update --quiet \
                && brew upgrade \
                && brew prune \
                && brew cleanup \
                && brew doctor"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# System operations & information

alias cleanupDS="find . -type f -name '*.DS_Store' -ls -delete" # Recursively delete .DS_Store files
alias afk="osascript -e 'tell application \"System Events\" to sleep'" # Lock screen

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Web development

alias editHosts='sudo code /etc/hosts'      # Edit /etc/hosts file

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Update applications

alias update="sudo softwareupdate --install --all \
            && brew update \
            && brew upgrade \
            && brew cleanup \
            && npm install -g npm \
            && npm update -g"


# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Docker compose aliases

############################################################################
#                                                                          #
#     # Usage:                                                             #
#     dc             : docker-compose                                      #
#     dcu            : docker-compose up -d                                #
#     dcd            : docker-compose down                                 #
#     dcr            : docker-compose run                                  #
#     dex <container>: execute a bash shell inside the RUNNING <container> #
#     di <container> : docker inspect <container>                          #
#     dim            : docker images                                       #
#     dip            : IP addresses of all running containers              #
#     dl <container> : docker logs -f <container>                          #
#     dnames         : names of all running containers                     #
#     dps            : docker ps                                           #
#     dpsa           : docker ps -a                                        #
#     drmc           : remove all exited containers                        #
#     drmid          : remove all dangling images                          #
#     drun <image>   : execute a bash shell in NEW container from <image>  #
#     dsr <container>: stop then remove <container>                        #
#                                                                          #
############################################################################

function dnames-fn {
	for ID in `docker ps | awk '{print $1}' | grep -v 'CONTAINER'`
	do
    	docker inspect $ID | grep Name | head -1 | awk '{print $2}' | sed 's/,//g' | sed 's%/%%g' | sed 's/"//g'
	done
}

function dip-fn {
    echo "IP addresses of all named running containers"

    for DOC in `dnames-fn`
    do
        IP=`docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}} {{end}}' "$DOC"`
        OUT+=$DOC'\t'$IP'\n'
    done
    echo -e $OUT | column -t
    unset OUT
}

function dex-fn {
	docker exec -it $1 ${2:-bash}
}

function di-fn {
	docker inspect $1
}

function dl-fn {
	docker logs -f $1
}

function drun-fn {
	docker run -it $1 $2
}

function dcr-fn {
	docker-compose run $@
}

function dsr-fn {
	docker stop $1;docker rm $1
}

function drmc-fn {
       docker rm $(docker ps --all -q -f status=exited)
}

function drmid-fn {
       imgs=$(docker images -q -f dangling=true)
       [ ! -z "$imgs" ] && docker rmi "$imgs" || echo "no dangling images."
}

# in order to do things like dex $(dlab label) sh
function dlab {
       docker ps --filter="label=$1" --format="{{.ID}}"
}

function dc-fn {
        docker-compose $*
}

alias dc=dc-fn
alias dcu="docker-compose up -d"
alias dcd="docker-compose down"
alias dcr=dcr-fn
alias dex=dex-fn
alias di=di-fn
alias dim="docker images"
alias dip=dip-fn
alias dl=dl-fn
alias dnames=dnames-fn
alias dps="docker ps"
alias dpsa="docker ps -a"
alias drmc=drmc-fn
alias drmid=drmid-fn
alias drun=drun-fn
alias dsp="docker system prune --all"
alias dsr=dsr-fn
