#!/bin/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Enable `vi` editing mode.
# https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Readline-vi-Mode

set -o vi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Automatically prepend `cd` to directory names.

setopt -s autocd

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Autocorrect typos in path names when using the `cd` command.

setopt -s cdspell

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Check the window size after each command and, if necessary, update
# the values of `LINES` and `COLUMNS`.

setopt -s checkwinsize

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Save all lines of a multiple-line command in the same history entry.

setopt -s cmdhist

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Include filenames beginning with a "." in the filename expansion.

setopt -s dotglob

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Use extended pattern matching features.

setopt -s extglob

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Append to the history file rather then overwriting it.

setopt -s histappend

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Do not attempt to search the PATH for possible completions when
# completion is attempted on an empty line.

setopt -s no_empty_cmd_completion

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Match filenames in a case-insensitive fashion when performing
# filename expansion.

setopt -s nocaseglob
